import{a as S,i as u,S as I}from"./assets/vendor-95dc692e.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function c(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=c(e);fetch(e.href,o)}})();async function m(t,n){const e="https://pixabay.com"+"/api/",o={key:"43041938-51a06b63921488a862c0fcc6d",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,lang:"en",page:n,per_page:15};return(await S.get(e,{params:o})).data}let v=!0;function p(t){return t.length===0?(d(),u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),catchData=!1):t.map(({webformatURL:c,largeImageURL:r,tags:e,likes:o,views:a,comments:L,downloads:b})=>`
    <li class="gallery-item">
    <a class="gallery-link" href="${r}">
    <img class="gallery-image" src="${c}" alt="${e}" />
    </a>
    <div class="content-image">
    <p class="pege-item">Likes<span class="inf-item">${o}</span></p>
    <p class="pege-item">Views<span class="inf-item">${a}</span></p>
    <p class="pege-item">Comments<span class="inf-item">${L}</span></p>
    <p class="pege-item">Downloads<span class="inf-item">${b}</span></p>
    </div>
    </li>
    `).join("")}let l,i=1,f=0;const M=15,s={formElem:document.querySelector("form"),list:document.querySelector(".gallery-image"),loadItem:document.querySelector(".loader-cont"),btnLoad:document.querySelector(".btn-primary"),loadIcon:document.querySelector(".content-loader"),loadIconMore:document.querySelector(".loader")};s.formElem.addEventListener("submit",w);s.btnLoad.addEventListener("click",q);async function w(t){if(t.preventDefault(),g(),i=1,l=t.target.elements.search.value.trim(),s.list.innerHTML="",!l&&v){d(),u.info({message:"Line is empty, enter a value",position:"topLeft"}),s.list.innerHTML="";return}try{O();const n=await m(l,i);f=Math.ceil(n.totalHits/M),s.list.insertAdjacentHTML("beforeend",p(n.hits)),y.refresh(),h(),d()}catch(n){console.log(n)}t.target.reset()}async function q(){try{i+=1,D();const t=await m(l,i);s.list.insertAdjacentHTML("beforeend",p(t.hits)),P(),y.refresh()}catch(t){console.log(t)}B(),h()}function h(){i>=f?(g(),u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):E()}function E(){s.btnLoad.classList.remove("hidden")}function g(){s.btnLoad.classList.add("hidden")}function O(){s.loadIcon.classList.remove("hidden")}function d(){s.loadIcon.classList.add("hidden")}function D(){s.loadIconMore.classList.remove("hidden")}function P(){s.loadIconMore.classList.add("hidden")}function B(){const t=s.list.firstChild.getBoundingClientRect().height;console.log(t),scrollBy({top:t*2,behavior:"smooth"})}const y=new I(".gallery-link",{captionsData:"alt",captionDelay:250,overlayOpacity:.8});
//# sourceMappingURL=commonHelpers.js.map
