import{a as b,i as m,S}from"./assets/vendor-95dc692e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();async function p(s,r){const e="https://pixabay.com"+"/api/",t={key:"43041938-51a06b63921488a862c0fcc6d",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,lang:"en",page:r,per_page:24};return(await b.get(e,{params:t})).data}let v=!0;function u(s){return s.length===0?(m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),catchData=!1):s.map(({webformatURL:c,largeImageURL:n,tags:e,likes:t,views:o,comments:h,downloads:L})=>`
    <li class="gallery-item">
    <a class="gallery-link" href="${n}">
    <img class="gallery-image" src="${c}" alt="${e}" />
    </a>
    <div class="content-image">
    <p class="pege-item">Likes<span class="inf-item">${t}</span></p>
    <p class="pege-item">Views<span class="inf-item">${o}</span></p>
    <p class="pege-item">Comments<span class="inf-item">${h}</span></p>
    <p class="pege-item">Downloads<span class="inf-item">${L}</span></p>
    </div>
    </li>
    `).join("")}let l,i=1,d=0;const E=24,a={formElem:document.querySelector("form"),list:document.querySelector(".gallery-image"),loadItem:document.querySelector(".loader-cont"),btnLoad:document.querySelector(".btn-primary")};a.formElem.addEventListener("submit",M);a.btnLoad.addEventListener("click",O);async function M(s){if(s.preventDefault(),g(),i=1,l=s.target.elements.search.value.trim(),a.list.innerHTML="",!l&&v){m.info({message:"Line is empty, enter a value",position:"topLeft"}),a.list.innerHTML="";return}try{const r=await p(l,i);d=Math.ceil(r.totalHits/E),a.list.insertAdjacentHTML("beforeend",u(r.hits)),y.refresh(),f()}catch(r){console.log(r)}s.target.reset()}async function O(){try{i+=1;const s=await p(l,i);a.list.insertAdjacentHTML("beforeend",u(s.hits)),y.refresh()}catch(s){console.log(s)}f()}function f(){i>=d?(g(),m.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}function w(){a.btnLoad.classList.remove("hidden")}function g(){a.btnLoad.classList.add("hidden")}const y=new S(".gallery-link",{captionsData:"alt",captionDelay:250,overlayOpacity:.8});
//# sourceMappingURL=commonHelpers.js.map
